name: "Setup test env"
description: "Setup test environment for actions"

inputs:
  node-version:
    description: "Node version"
    required: false
    default: "20.11.0"
  cache-extension:
    description: "Extension for fetching cached dependencies"
    required: true

runs:
  using: "composite"
  steps:
    - name: Cancel Previous Runs
      uses: styfle/cancel-workflow-action@0.11.0
      with:
        access_token: ${{ github.token }}

    - name: Setup Node.js environment
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node-version }}
        cache: "yarn"

    - name: Install dependencies
      uses: ./.github/actions/cache-deps
      with:
        extension: ${{ inputs.cache-extension }}
